language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
- openssl aes-256-cbc -k "$super_secret_password" -in se234.pem.enc -out se234.pem
  -d
- sudo chmod 400 se234.pem
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t dto80/htmltest .
- docker push dto80/htmltest
after_success:
- docker run -p 8088:80 -d dto80/htmltest:latest
- ls -l
- scp -i "se234.pem" -r html/* ubuntu@54.71.80.147:/var/www/html
service: docker
env:
  global:
  - secure: A9UT1Lb11AwhvG+7ap86hcxWjb7/Yuf8dsNvTxeXJO+vj7UkPnoHbHwHh5LreOvAP8MbJPuyZUVxu5TwhX+Jx29+dVmuk7GkoZRYUER64rUFmgu2kHUn5d+z5KK4FI6wz3my5lVm0tSJ7H39ZwwzX62vX3ZPEaDU4JvE0pvclfU4IFj8WFeXeX7unvAtYiScl19JzXBnHlEaXQcYc7fgIePYa1aScfhRC05a2O+AP3EJf8f0yR70oQwl31aejg4WbPDRQbJUTJ3trBjlpOm1rMpGli8NUqVfGkE78ERTW99GfHqZ9pdIhE6iYX+yxceiQlLz7xgNdVdmxPxcUEnuUgKw5mjiKaC+eqniUYozvCIHb9EQGaqppts01GayPRjTj9FIQJEFLlp8Ad5CBLK3LDGdhsicbqB0KRjUtcsRbW2qhCNSw5NzBmatEvpmi25Wp0mDM5fMlBK9/5iBDzmQ2sgda87eEdlOp6/Yhk5sEYGDVavZsdNYTVz88EZdQ0LDEva/vOzUQhsyIgYG7S+KMu5bWVuPF7B/mfm6zXNlfnSSyYq5DeG3+URbhvWb96TchL9bAOOTvgYjV9QZixe1mwjABoC1VrG5WTynXFa5pQEWwxkD+4SZDXY2xTbxKkdHHazjgzGG969ApwfochotMGjhgcq5mNA8v+aO7P6Zi/M=
  - secure: FWoMfrAFLQm8yiv/j2PCNnLYkxFjvR7wlUnNxqAtdvUqRKRds5GM0H0AaZ4yQA+9FHe3gurJzvrPJxcwrhv/WoqMW0cfwNWPeXCI4vxP/+vp1kMhGGVTNWr17FgTa4c5HJzeywx0HoAI1cck73NhhSR3MslprEMt1QiMIqL+MdtJi0SE98MGKO2vbkHLuQMNirn3CT+2awC+5vP7VJmVnNX5WggE8SKV1mLs2qRHpt7zZ5vxxyya23J+xhL3r3jD+tQSrFQxtJ1z+P18L/Zlg7uiguWR4KeqJD9Y3sTt+S/3Sa1MlFHzfDEHhJzrTnyDoLqz/HrTewPApHDZ6sbuxaut4W0chFOOzpktBm8zAhUgrApoDWE49EVovUhoNJiVuXiIkx451SUKAadTv1iNblr283JiTSV03MgcGn7bpX73cvRjU6mtLHTB+/hm5HRxeZSL5Fw1+BiKSWL8GL1bKBOucnxK4x4bdSiFYZd9qU6iWldtUFUSVHS+hv8q+G0FthkCR5VoxVw4jlFch2mEMQnHKEBkBmXZ8ukfaFuNLnfka7NfJQHulWU7Qsg4VW8dS/9bVHe3GRHm9eeBdQRfZEb5Pw9r4CcOTZoTiaHRTvLn4LFd3zJdnL4okwcJb58+rWmje1DVxHRXIpmjSktJrO/h8j7uNN7AGVtL0l/iyQQ=
  - secure: qlazzi0ADfVhxjjrMNX/lGydq/CRhjHjhOsxXslEyL0tdvPdbMWRMSC82/kch72uZ7gP6oo2Gm3HYntgUgC+pgccWZyP8ThImpnixI+R3DGwiJGoMZUnT3YtUk/LW8Y9FeukNnIxvYXGzdQMrNZZANYzF6D0fvPKZTx1/kB60NDxn9CMDvdz43bVMUTpAiV5qCDlV4SCQSkl1cL/C689sBMX+mMRbEZqtU3fCU6P8mbY+gGeMbjHNOIIx0O1RkYDlK0eCifQhPyAwUrFNNM1MNfEwsRQRsBRtgNQreyR4VJ4Rj9UrBFMNC2cgctcU1CIEGOvVe2NcG6wApRAifV4IZ6xfZCRLGPuko8ifGaW915xQtcnTPlTg6IyLBKKG/HhH+2Xa+EUTMhvgiwAMq2ydyEvwpS0JRVAob1zLRO7W7i0oKdPOEtolj/8/3k3kR+X0i8gacSX/EiZii0zXEBs9ohcvFFEq9gV6IQW9U78+mME5BtGUDkx/UOTqRO9QfoGMAvbLJ9NrkUp6vwHfjEDyapnEoZfS3gLeqFAsjY18PrLIXhABM9+kD3wbZqzVWzgKl7cozYNfJgst9zkiqy9/kBeHEXrD79cDYuDAdV442Uwf8a5v56qq1vrpT9Nj03QfihmEOCYN2uJEDGUxbV6P54p0xEd0DTfPycilF0zSfI=
addons:
  ssh_known_hosts:
  - 54.71.80.147
dd:
  secure: mMXqfdxmGYErCeP+hvhDdBSIHya+2YR1u9ud506Mrxlr+ga/P4kyZww30e4ZM6EDLDOn2JUPDF+ycyETRBzevBw38aJGf96V5Z9oQaSkJA0OpY4hfkTnssXQbj5/NHKHuu1ErB2ZO71gSPNGvkZQ8vvlSIMX6OycazTOTgyUdrgE1e+jG4rNZClX9jxmwSucrsD7Vway5O/uiyPv+Mcfvux9uQaehfXu6l4MhitoUXNY2Pt3XJKCJFByOk7RTa5mfj5k6/M6Docxxr5i+TZFPOttLN5iSFgiqzNwJv9Y05ieN2bGY0+metqlX49AozkDNsaVIytKs+Svm+urDw9ZQOsxLLe+jXBaurJxA/N7QoLJ0xwT1PIoiSDY67ycsZJuAHKAVQq5i3XsxExYTSjXJ7zDHvB873RJzcvH6CUHbs2uzB0QsDiCsn7MuOgpJbeUnlTMbIWyYUGluCiR1gqliJGRzEIXUdED82634fMSuXaH0Zo5MURmqnfMkBV4Ld0NLOlm8KwnwOJiJX1ztMWCPkp8nYy24GTh6Y6wSpljmjAyqHXzx/7ZnQoV3UcQB2tv/pnh1L36IXR3DTogmLKxiLvt6L5fJkcM+jcKnHrOneXDSloYeRfAR8/XcHUJ0n69SKnWhkS9v17lDslUJv6xYgPjJTiBvzpbq3etFHz8UiE=
